spring.application.name=webpage
spring.main.banner-mode=off

server.server-header=
spring.web.error.whitelabel.enabled=false

# Reduce logging level
logging.level.root=INFO

# No color in logs
spring.output.ansi.enabled=never